name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
    - name: Generate build files
      uses: thatisuday/go-cross-build@v1
      with:
          platforms: 'linux/amd64, darwin/amd64, windows/amd64'
          package: ''
          name: 'WordsImport-${{ env.GITHUB_RUN_NUMBER }}'
          compress: 'false'
      
